# Generated by Django 5.2.15 on 2026-08-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AlterModelOptions(
            name='outboxmessage',
            options={
                'verbose_name': 'Исходящее сообщение',
                'verbose_name_plural': 'Исходящие сообщения',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='idempotency_key',
            field=models.CharField(
                max_length=255, verbose_name='Ключ идемпотентности'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=models.JSONField(verbose_name='Тело вебхука'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Получено'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Создано'
            ),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outbox_messages',
                to='webhooks.event',
                verbose_name='Событие',
            ),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Ожидает отправки')],
                default='pending',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
