# Generated by Django 5.2.15 on 2026-08-05 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'webhooks',
            '0002_alter_event_options_alter_outboxmessage_options_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                (
                    'target_url',
                    models.URLField(
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=['https', 'http']
                            )
                        ],
                        verbose_name='URL',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активный'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создано'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Обновлено'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('name',), name='uniq_subscriber_name'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('target_url__startswith', 'https://'),
                            ('target_url__startswith', 'http://'),
                            _connector='OR',
                        ),
                        name='subscriber_target_url_scheme',
                    ),
                ],
            },
        ),
    ]
