# Generated by Django 5.2.15 on 2026-08-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhooks', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('started', 'Начата'),
                            ('succeeded', 'Завершена успешно'),
                            ('failed', 'Завершена с ошибкой'),
                        ],
                        default='started',
                        max_length=20,
                        verbose_name='Статус попытки',
                    ),
                ),
                (
                    'attempt_no',
                    models.PositiveSmallIntegerField(
                        verbose_name='Номер попытки'
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Начата'
                    ),
                ),
                (
                    'http_status',
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name='Статус ответа'
                    ),
                ),
                (
                    'error',
                    models.CharField(
                        max_length=100, verbose_name='Причина отказа'
                    ),
                ),
                (
                    'finished_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Завершено'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='delivery_attempts',
                        to='webhooks.event',
                        verbose_name='Событие',
                    ),
                ),
                (
                    'subscriber',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='delivery_attempts',
                        to='webhooks.subscriber',
                        verbose_name='Подписчик',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Попытка доставки сообщения',
                'verbose_name_plural': 'Попытки доставки сообщений',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('event', 'subscriber', 'attempt_no'),
                        name='uniq_delivery_attempt_number',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('attempt_no__gte', 1)),
                        name='delivery_attempt_no_gte_1',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('status__in', ['started', 'succeeded', 'failed'])
                        ),
                        name='delivery_attempt_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('finished_at__isnull', True),
                                ('status', 'started'),
                            ),
                            models.Q(
                                ('finished_at__isnull', False),
                                ('status__in', ['succeeded', 'failed']),
                            ),
                            _connector='OR',
                        ),
                        name='delivery_attempt_completion_consistent',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('http_status__isnull', True),
                            models.Q(
                                ('http_status__gte', 100),
                                ('http_status__lte', 599),
                            ),
                            _connector='OR',
                        ),
                        name='delivery_attempt_http_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('error', ''),
                                ('http_status__isnull', True),
                                ('status', 'started'),
                            ),
                            models.Q(
                                ('error', ''),
                                ('http_status__isnull', False),
                                ('status', 'succeeded'),
                            ),
                            models.Q(
                                ('status', 'failed'),
                                models.Q(
                                    ('http_status__isnull', False),
                                    models.Q(('error', ''), _negated=True),
                                    _connector='OR',
                                ),
                            ),
                            _connector='OR',
                        ),
                        name='delivery_attempt_result_consistent',
                    ),
                ],
            },
        ),
    ]
