# Generated by Django 5.2.15 on 2026-09-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhooks', '0004_deliveryattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryattempt',
            options={
                'verbose_name': 'Delivery attempt',
                'verbose_name_plural': 'Delivery attempts',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='outboxmessage',
            options={
                'verbose_name': 'Outbox message',
                'verbose_name_plural': 'Outbox messages',
            },
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.RemoveConstraint(
            model_name='outboxmessage',
            name='outbox_status_valid',
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='attempt_no',
            field=models.PositiveSmallIntegerField(
                verbose_name='Attempt number'
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='error',
            field=models.CharField(
                max_length=100, verbose_name='Failure reason'
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='event',
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='delivery_attempts',
                to='webhooks.event',
                verbose_name='Event',
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='finished_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Finished at'
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='http_status',
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name='Response status'
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='started_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Started at'
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(
                choices=[
                    ('started', 'Started'),
                    ('succeeded', 'Succeeded'),
                    ('failed', 'Failed'),
                ],
                default='started',
                max_length=20,
                verbose_name='Attempt status',
            ),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='subscriber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='delivery_attempts',
                to='webhooks.subscriber',
                verbose_name='Subscriber',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='idempotency_key',
            field=models.CharField(
                max_length=255, verbose_name='Idempotency key'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=models.JSONField(verbose_name='Webhook body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Received at'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created at'
            ),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outbox_messages',
                to='webhooks.event',
                verbose_name='Event',
            ),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Awaiting publication'),
                    ('published', 'Published'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created at'
            ),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Updated at'
            ),
        ),
        migrations.AddConstraint(
            model_name='outboxmessage',
            constraint=models.CheckConstraint(
                condition=models.Q(('status__in', ['pending', 'published'])),
                name='outbox_status_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='outboxmessage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('published_at__isnull', True), ('status', 'pending')
                    ),
                    models.Q(
                        ('published_at__isnull', False),
                        ('status', 'published'),
                    ),
                    _connector='OR',
                ),
                name='outbox_publication_consistent',
            ),
        ),
    ]
