# Generated by Django 5.2.15 on 2026-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhooks', '0005_outbox_publication_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outboxmessage',
            index=models.Index(
                condition=models.Q(('status', 'pending')),
                fields=['created_at'],
                name='outbox_pending_created_at',
            ),
        ),
    ]
